// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title ProofOfAudit
 * @dev Stores cryptographic hashes of smart contract security audits on-chain.
 */
contract ProofOfAudit {
    
    struct AuditRecord {
        address auditedContract; // 0x0 if it's raw source code instead of deployed contract
        bytes32 reportHash;      // SHA256 hash of the JSON vulnerability report generated by Web3 Guard
        uint256 timestamp;
    }

    mapping(uint256 => AuditRecord) public audits;
    uint256 public nextAuditId;
    
    address public owner; 
    address public pendingOwner;

    error Unauthorized();
    error NotPendingOwner();
    error InvalidAuditId();
    error EmptyReportHash();
    error InvalidNewOwner();

    event AuditStored(uint256 indexed auditId, address indexed auditedContract, bytes32 reportHash, uint256 timestamp);
    event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    modifier onlyOwner() {
        if (msg.sender != owner) revert Unauthorized();
        _;
    }

    constructor() {
        owner = msg.sender;
        emit OwnershipTransferred(address(0), msg.sender);
    }

    /**
     * @dev Starts the ownership transfer of the contract to a new account.
     */
    function transferOwnership(address newOwner) public virtual onlyOwner {
        if (newOwner == address(0)) revert InvalidNewOwner();
        pendingOwner = newOwner;
        emit OwnershipTransferStarted(owner, newOwner);
    }

    /**
     * @dev The new owner accepts the ownership transfer.
     */
    function acceptOwnership() public virtual {
        if (msg.sender != pendingOwner) revert NotPendingOwner();
        emit OwnershipTransferred(owner, pendingOwner);
        owner = pendingOwner;
        pendingOwner = address(0);
    }

    /**
     * @dev Stores a new audit record on the blockchain. Only the authorized backend can call this.
     * @param _auditedContract The address of the contract that was audited.
     * @param _reportHash The SHA256 hash of the generated audit report.
     */
    function storeAuditHash(address _auditedContract, bytes32 _reportHash) public onlyOwner returns (uint256) {
        if (_reportHash == bytes32(0)) revert EmptyReportHash();
        
        uint256 currentId = nextAuditId;
        
        audits[currentId] = AuditRecord({
            auditedContract: _auditedContract,
            reportHash: _reportHash,
            timestamp: block.timestamp
        });

        emit AuditStored(currentId, _auditedContract, _reportHash, block.timestamp);
        
        nextAuditId = currentId + 1; 
        
        return currentId;
    }

    /**
     * @dev Retrieves an audit record by its ID.
     */
    function getAudit(uint256 _auditId) public view returns (address, bytes32, uint256) {
        if (_auditId >= nextAuditId) revert InvalidAuditId();
        AuditRecord memory record = audits[_auditId];
        return (record.auditedContract, record.reportHash, record.timestamp);
    }
}
